#include<lpc21xx.h>
typedef unsigned char uc;
typedef unsigned int ui;
typedef unsigned short int usi;
struct rtc{
uc s;
uc m;
uc h;
uc day;
uc date;
uc mon;
uc y;
uc me;
};
void rtc_date(void );
void rtc_time(void);
unsigned int bcd_to_dec(int v);
void delay_sec(ui sec);
void delay_ms(ui ms);
void adc_init(void);
unsigned int adc_read(unsigned char ch);
void uart0_init(int baud);
void uart0_tx(uc data);
uc uart0_rx(void);
void uart0_tx_string(char *p);
void uart0_integer(int num);
void uart0_float(float f);
void i2c_init(void);
void i2c_write(unsigned char sa,unsigned char mr,unsigned char data);
unsigned char i2c_read(unsigned char sa,unsigned char mr);
void spi_init(void);
unsigned char spi_data(unsigned char data);
unsigned short int spi_read(unsigned char ch);
void lcd_data(unsigned char data);
void lcd_cmd(unsigned char cmd);
void lcd_string( char *p);
void lcd_int(int n);
void lcd_float(float f);
void lcd_init(void);
void config_vic_for_timer1(void);
void config_timer1_intr(void);
